project:
  type: website
  output-dir: docs

website:
  title: ""
  favicon: "/img/logo.svg"
  navbar:
    logo: "/img/logo.svg"
    left:
      - href: index.qmd
        text: Home
      - href: portfolio.qmd
        text: Works
  page-footer:
    background: "#2e70f9"
    left: |
      [![](/img/logo_white.svg){height="20"}](index.html)
    center:
      - text: "Works"
        href: portfolio.qmd

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true
